name: Build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      # Configures gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      # Run "gradlew build"
      - name: Execute Gradle
        run: ./gradlew build
      - id: artifact
        name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: KitRecommender.jar
          path: plugin/build/libs/KitRecommender.jar
          if-no-files-found: error
